import "../src/app/globals.css";
import { Provider } from "react-redux";
import { SessionProvider } from "next-auth/react";
import store from "../store";
import DefaultLayout from "../layout/default";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function App({ Component, pageProps: { session, ...pageProps } }) {
    return (
        <div className={poppins.className}>
            <SessionProvider session={session}>
                <Provider store={store}>
                    <DefaultLayout>
                        <Component {...pageProps} />
                    </DefaultLayout>
                </Provider>
            </SessionProvider>
        </div>
    );
}
